using System;
using System.IO;
using System.Diagnostics;

namespace AST.Parsers.Utilities
{
    /// <summary>
    /// Misc scripting utilities
    /// </summary>
    public static class ScriptUtilities
    {
        /// <summary>
        /// Directly execute a script file in a sub process
        /// </summary>
        /// <param name="cmd">the command to be executed</param>
        /// <param name="arguments">String representing the collection of arguments to provide</param>
        /// <returns>String containing the result from the standard output</returns>
        public static string RunScript(string cmd, string arguments)
        {
            ProcessStartInfo start = new()
            {
                FileName = cmd,
                Arguments = arguments,
                UseShellExecute = false,// Do not use OS shell
                CreateNoWindow = true, // We don't need new window
                RedirectStandardOutput = true,// Any output, generated by application will be redirected back
            };
            using Process process = Process.Start(start);
            using StreamReader reader = process.StandardOutput;
            string result = reader.ReadToEnd();
            return result;
        }
    }

}
